### ISSUE TITLE
Function to scan for Wi-Fi access points

### ISSUE THREAD

**Issue by josephroberts** [resin-io-modules/network_manager#1]
Write a function that uses the NM DBus API to scan for Wi-Fi access points.
It should return a result containing a list of access points where each access point is a tuple containing:
- SSID
- Signal strength
- Security protocol

NM CLI command: `nmcli device wifi list`

Questions:
- Should the list be ordered, should this be optional?
    - Alphabetically
    - Signal strength

**Comment by josephroberts** [comment]
@zozo123 could you use this https://developer.gnome.org/NetworkManager/unstable/gdbus-org.freedesktop.NetworkManager.AccessPoint.html

**Comment by zozo123** [comment]
As discussed with @josephroberts, we will first add a capability to retrieve a map of [device type](https://developer.gnome.org/NetworkManager/unstable/nm-dbus-types.html#NMDeviceType) to its `dbus::Path`.

Then we will handle the wireless (type 2) interface and retrieve the Access Point's [properties](https://developer.gnome.org/NetworkManager/unstable/gdbus-org.freedesktop.NetworkManager.AccessPoint.html)

**Comment by josephroberts** [comment]
https://github.com/resin-io/hq/pull/453

**Comment by majorz** [comment]
Implemented in a8201966c3d1cd4fdc21c3e832345f4b718f5ec3
