### ISSUE TITLE
Refactor the code to use the dbus lib types

### ISSUE THREAD

**Issue by zozo123** [resin-io-modules/network_manager#34]
Use the dbus types in order to avoid cumbersome consuming of the data e.g:
```

pub fn dbus_path_to_string(path: dbus::Path) -> String {
path.as_cstr().to_str().unwrap().to_string()
}
```

**Comment by josephroberts** [comment]
https://github.com/resin-io/hq/pull/453

**Comment by majorz** [comment]
Closing it in favor of the code committed with PRs #47 and #44.
